### ISSUE TITLE
Dokumentacja technicza - javadocs

### ISSUE THREAD

**Issue by sniochup** [AdrianKarolewski/ScenarioQualityCheckerI8_2_2021#13]
**7 klas / interfejsów posiadających pełną dokumentację techniczną**

W komentarzach proszę pisać nazwy klasy/interfejsów do których stworzono pełną dokumentacje, zaleca się tworzenie jej na bierząco podczas pisania kodu.

**Comment by sniochup** [comment]
pl.put.poznan.sqc.rest.ScenarioQualityCheckerController

**Comment by sniochup** [comment]
pl.put.poznan.sqc.logic.Numbered

**Comment by sniochup** [comment]
pl.put.poznan.sqc.logic.Simplified

**Comment by julialamperska** [comment]
Klasy i interfejsy posiadające pełną dokumentację techniczną:
1. /logic/Keyword.java
2. /logic/NoActor.java
3. /logic/ScenarioInterface.java
4. /logic/StepsCount.java
5. /rest/ScenarioQualityCheckerController.java
6. /scenario/Actor.java
7. /scenario/Scenario.java
8. /scenario/Step.java
