### ISSUE TITLE
Spisanie akcji naprawczych - retrospektywy

### ISSUE THREAD

**Issue by sniochup** [AdrianKarolewski/ScenarioQualityCheckerI8_2_2021#15]

**Comment by sniochup** [comment]
[Sprint I - retrospektywa](https://github.com/AdrianKarolewski/ScenarioQualityCheckerI8_2_2021/wiki/Sprint-I#retrospective---things-to-improve)
Do sprawdzenia: @julialamperska @AdrianKarolewski @Filip87299

**Comment by julialamperska** [comment]
errors corrected
