### ISSUE TITLE
Testy jednostkowe

### ISSUE THREAD

**Issue by sniochup** [AdrianKarolewski/ScenarioQualityCheckerI8_2_2021#17]
- [x] Stworzono 2 klasy testujące i 20 metod testujących
- [x] Przetestowanie 10 wywołań metod z zewnętrznych klas za pomocą mock objectów

**Comment by julialamperska** [comment]
dodano 10 testów do klasy NoActor (@AdrianKarolewski ) i 12 testów do klasy Keyword, wszystkie za pomocą mock objectów
