### ISSUE TITLE
Zliczanie kroków scenariusza

### ISSUE THREAD

**Issue by AdrianKarolewski** [AdrianKarolewski/ScenarioQualityCheckerI8_2_2021#2]
Jako analityk mogę sprawdzić ile kroków zawiera cały scenariusz (łącznie z pod-scenariuszami), aby ocenić jak bardzo jest skomplikowany

- [x]  Obsługa zapytania - liczba kroków

- [x]  Zliczania kroków scenariusza

- [x]  Model odpowiedzi - liczba kroków

**Comment by AdrianKarolewski** [comment]
- [ ]  Obsługa zapytania - liczba kroków

- [ ]  Zliczania kroków scenariusza

- [ ]  Model odpowiedzi - liczba kroków

**Comment by sniochup** [comment]
Added on branch functionalities
