### ISSUE TITLE
Zliczanie decyzji warunkowych w scenariuszu

### ISSUE THREAD

**Issue by julialamperska** [AdrianKarolewski/ScenarioQualityCheckerI8_2_2021#3]
Jako analityk mogę sprawdzić ile kroków zawiera słowa kluczowe, aby dowiedzieć się jak wiele decyzji warunkowych znajduje się w scenariuszu.

- [x] Sformułowanie modelu pytania
- [x] Wykonanie operacji sprawdzania słów kluczowych i zliczania decyzji warunkowych
- [x] Pobranie informacji z serwera

**Comment by sniochup** [comment]
Added on branch functionalities
